
import org.jpl7.Atom;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kira2
 */
public class MainLayout extends javax.swing.JFrame {

    /**
     * Creates new form MainLayout
     */
    public MainLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new JButton();
        jPanel2 = new javax.swing.JPanel();
        Boton1 = new JButton();
        Boton2 = new JButton();
        Boton3 = new JButton();
        Boton4 = new JButton();
        Boton6 = new JButton();
        Boton5 = new JButton();
        Boton7 = new JButton();
        Boton8 = new JButton();
        Boton9 = new JButton();
        Boton10 = new JButton();
        Boton11 = new JButton();
        Boton12 = new JButton();
        Boton13 = new JButton();
        Boton14 = new JButton();
        Boton15 = new JButton();
        Boton16 = new JButton();
        Boton17 = new JButton();
        Boton18 = new JButton();
        Boton19 = new JButton();
        Boton20 = new JButton();
        Boton21 = new JButton();
        Boton22 = new JButton();
        Boton23 = new JButton();
        Boton24 = new JButton();
        Boton25 = new JButton();
        Boton26 = new JButton();
        Boton27 = new JButton();
        Boton28 = new JButton();
        Boton29 = new JButton();
        Boton30 = new JButton();
        Boton31 = new JButton();
        Boton32 = new JButton();
        Boton33 = new JButton();
        Boton34 = new JButton();
        Boton35 = new JButton();
        Boton36 = new JButton();
        Boton37 = new JButton();
        Boton38 = new JButton();
        Boton39 = new JButton();
        Boton40 = new JButton();
        Boton41 = new JButton();
        Boton42 = new JButton();
        Boton43 = new JButton();
        Boton44 = new JButton();
        Boton45 = new JButton();
        Boton46 = new JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Punto A");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Punto B");

        jTextField2.setText("jTextField2");

        jButton2.setText("Buscar Ruta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton1.setBackground(new java.awt.Color(255, 0, 51));
        Boton1.setText("...");
        jPanel2.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 30, -1));

        Boton2.setBackground(new java.awt.Color(255, 0, 51));
        Boton2.setText("...");
        jPanel2.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 30, -1));

        Boton3.setBackground(new java.awt.Color(255, 0, 51));
        Boton3.setText("...");
        jPanel2.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 30, -1));

        Boton4.setBackground(new java.awt.Color(255, 0, 51));
        Boton4.setText("...");
        jPanel2.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 30, -1));

        Boton6.setBackground(new java.awt.Color(255, 0, 51));
        Boton6.setText("...");
        jPanel2.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 30, -1));

        Boton5.setBackground(new java.awt.Color(255, 0, 51));
        Boton5.setText("...");
        jPanel2.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 30, -1));

        Boton7.setBackground(new java.awt.Color(255, 0, 51));
        Boton7.setText("...");
        jPanel2.add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 30, -1));

        Boton8.setBackground(new java.awt.Color(255, 0, 51));
        Boton8.setText("...");
        jPanel2.add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 30, -1));

        Boton9.setBackground(new java.awt.Color(255, 0, 51));
        Boton9.setText("...");
        jPanel2.add(Boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 30, -1));

        Boton10.setBackground(new java.awt.Color(255, 0, 51));
        Boton10.setText("...");
        jPanel2.add(Boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 30, -1));

        Boton11.setBackground(new java.awt.Color(255, 0, 51));
        Boton11.setText("...");
        jPanel2.add(Boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 30, -1));

        Boton12.setBackground(new java.awt.Color(255, 0, 51));
        Boton12.setText("...");
        jPanel2.add(Boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, -1));

        Boton13.setBackground(new java.awt.Color(255, 0, 51));
        Boton13.setText("...");
        jPanel2.add(Boton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 30, -1));

        Boton14.setBackground(new java.awt.Color(255, 0, 51));
        Boton14.setText("...");
        jPanel2.add(Boton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 30, -1));

        Boton15.setBackground(new java.awt.Color(255, 0, 51));
        Boton15.setText("...");
        jPanel2.add(Boton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 30, -1));

        Boton16.setBackground(new java.awt.Color(255, 0, 51));
        Boton16.setText("...");
        jPanel2.add(Boton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 30, -1));

        Boton17.setBackground(new java.awt.Color(255, 0, 51));
        Boton17.setText("...");
        jPanel2.add(Boton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 30, -1));

        Boton18.setBackground(new java.awt.Color(255, 0, 51));
        Boton18.setText("...");
        jPanel2.add(Boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 30, -1));

        Boton19.setBackground(new java.awt.Color(255, 0, 51));
        Boton19.setText("...");
        jPanel2.add(Boton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 30, -1));

        Boton20.setBackground(new java.awt.Color(255, 0, 51));
        Boton20.setText("...");
        jPanel2.add(Boton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 30, -1));

        Boton21.setBackground(new java.awt.Color(255, 0, 51));
        Boton21.setText("...");
        jPanel2.add(Boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 30, -1));

        Boton22.setBackground(new java.awt.Color(255, 0, 51));
        Boton22.setText("...");
        jPanel2.add(Boton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 30, -1));

        Boton23.setBackground(new java.awt.Color(255, 0, 51));
        Boton23.setText("...");
        jPanel2.add(Boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 30, -1));

        Boton24.setBackground(new java.awt.Color(255, 0, 51));
        Boton24.setText("...");
        jPanel2.add(Boton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 30, -1));

        Boton25.setBackground(new java.awt.Color(255, 0, 51));
        Boton25.setText("...");
        jPanel2.add(Boton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 30, -1));

        Boton26.setBackground(new java.awt.Color(255, 0, 51));
        Boton26.setText("...");
        jPanel2.add(Boton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 30, -1));

        Boton27.setBackground(new java.awt.Color(255, 0, 51));
        Boton27.setText("...");
        jPanel2.add(Boton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 30, -1));

        Boton28.setBackground(new java.awt.Color(255, 0, 51));
        Boton28.setText("...");
        jPanel2.add(Boton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 220, 30, -1));

        Boton29.setBackground(new java.awt.Color(255, 0, 51));
        Boton29.setText("...");
        jPanel2.add(Boton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 30, -1));

        Boton30.setBackground(new java.awt.Color(255, 0, 51));
        Boton30.setText("...");
        jPanel2.add(Boton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 640, 30, -1));

        Boton31.setBackground(new java.awt.Color(255, 0, 51));
        Boton31.setText("...");
        jPanel2.add(Boton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 530, 30, -1));

        Boton32.setBackground(new java.awt.Color(255, 0, 51));
        Boton32.setText("...");
        jPanel2.add(Boton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, 30, -1));

        Boton33.setBackground(new java.awt.Color(255, 0, 51));
        Boton33.setText("...");
        jPanel2.add(Boton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 750, 30, -1));

        Boton34.setBackground(new java.awt.Color(255, 0, 51));
        Boton34.setText("...");
        jPanel2.add(Boton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 750, 30, -1));

        Boton35.setBackground(new java.awt.Color(255, 0, 51));
        Boton35.setText("...");
        jPanel2.add(Boton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, 30, -1));

        Boton36.setBackground(new java.awt.Color(255, 0, 51));
        Boton36.setText("...");
        jPanel2.add(Boton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 740, 30, -1));

        Boton37.setBackground(new java.awt.Color(255, 0, 51));
        Boton37.setText("...");
        jPanel2.add(Boton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 730, 30, -1));

        Boton38.setBackground(new java.awt.Color(255, 0, 51));
        Boton38.setText("...");
        jPanel2.add(Boton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 730, 30, -1));

        Boton39.setBackground(new java.awt.Color(255, 0, 51));
        Boton39.setText("...");
        jPanel2.add(Boton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 30, -1));

        Boton40.setBackground(new java.awt.Color(255, 0, 51));
        Boton40.setText("...");
        jPanel2.add(Boton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 30, -1));

        Boton41.setBackground(new java.awt.Color(255, 0, 51));
        Boton41.setText("...");
        jPanel2.add(Boton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 30, -1));

        Boton42.setBackground(new java.awt.Color(255, 0, 51));
        Boton42.setText("...");
        jPanel2.add(Boton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 30, -1));

        Boton43.setBackground(new java.awt.Color(255, 0, 51));
        Boton43.setText("...");
        jPanel2.add(Boton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 30, -1));

        Boton44.setBackground(new java.awt.Color(255, 0, 51));
        Boton44.setText("...");
        jPanel2.add(Boton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 30, -1));

        Boton45.setBackground(new java.awt.Color(255, 0, 51));
        Boton45.setText("...");
        jPanel2.add(Boton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 740, 30, -1));

        Boton46.setBackground(new java.awt.Color(255, 0, 51));
        Boton46.setText("...");
        jPanel2.add(Boton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 30, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kira2\\Downloads\\practica6-Navegador\\Declatarive-Homework\\src\\MAPA SANTATECLA - Edited.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setButtonsInvisible();
        String valorTextField1 = jTextField1.getText();
        String valorTextField2 = jTextField2.getText();
        System.out.println("El valor de jTextField1 es: " + valorTextField1);
        System.out.println("El valor de jTextField2 es: " + valorTextField2);
        String tl = "consult('src/BaseConocimiento.pl')";
        Query ql = new Query(tl);
        if (!ql.hasSolution()){
            System.out.println("base de conocimiento no disponible");
        }
        else {
            System.out.println("Base encontrada");
            Variable X = new Variable(); // X es una variable de Prolog que capturará el resultado.
            Variable rutaFinal = new Variable("RutaFinal");

            Query q2 = new Query(
                    "consulta_ruta",
                    new Term[] {
                            new Atom(valorTextField1), // academia_nacional_de_seguridad_publica
                            new Atom(valorTextField2), // policlinica_casa_de_la_salud
                            rutaFinal
                    }
            );

            Map<String, Term> solution = q2.oneSolution();
            if (solution != null) {
                // Obtén el término asociado con la variable rutaFinal
                Term rutaTerm = solution.get(rutaFinal.name());

                // Convierte el término a un array de términos (si es una lista Prolog)
                Term[] rutaArray = rutaTerm.toTermArray();

                // Si prefieres, puedes convertir cada término del array a su representación en String
                String[] rutaStrings = new String[rutaArray.length];
                for (int i = 0; i < rutaArray.length; i++) {
                    rutaStrings[i] = rutaArray[i].toString();
                }
                showButtons(rutaStrings);
                // Ahora, puedes procesar rutaStrings como cualquier otro array de Strings en Java
                System.out.println("Ruta final: " + Arrays.toString(rutaStrings));
            } else {
                System.out.println("No se encontraron rutas.");
            }


        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private Map<Integer, JButton> botonMap;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        MainLayout ml = new MainLayout();
        ml.setButtonsInvisible();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ml.setVisible(true);
            }
        });
    }
    private void showButtons(String[] rutaStrings){
         Map<String, Integer> lugares = new HashMap<>();

        // Agregar elementos al diccionario
        lugares.put("hospital_climatosa", 46);
        lugares.put("liceo_jorge_adalberto_lagos", 2);
        lugares.put("centro_comercial_portal_plaza", 4);
        lugares.put("servi_tecla", 43);
        lugares.put("novacentro_santa_tecla", 6);
        lugares.put("parque_daniel_hernandez", 13);
        lugares.put("plaza_el_carmen", 14);
        lugares.put("tessa", 8);
        lugares.put("policlinica_casa_de_la_salud", 9);
        lugares.put("policlinico_magisterial_de_santatecla", 10);
        lugares.put("clinica_medica_las_colonias", 12);
        lugares.put("polideportivo_santa_cecilia", 18);
        lugares.put("escuela_de_comunicacion_monica_herrera", 41);
        lugares.put("escuela_santa_cecilia", 16);
        lugares.put("colegio_belen", 19);
        lugares.put("plaza_el_cafetalon", 20);
        lugares.put("colegio_champagnat", 27);
        lugares.put("centro_comercial_las_aguilas", 22);
        lugares.put("parque_san_martin", 21);
        lugares.put("academia_nacional_de_seguridad_publica", 23);
        lugares.put("el_cafetalon", 25);
        lugares.put("parque_acuatico_el_cafetalon", 29);
        lugares.put("alberto_masferrer_centro_escolar_catolico", 30);
        lugares.put("itca_fepade", 31);
        lugares.put("escuela_de_taekwando", 28);
        lugares.put("centro_escolar_marcelino_garcia_flamenco", 35);
        lugares.put("puma_energy", 32);
        lugares.put("hospital_nacional_san_rafael", 33);
        lugares.put("instituto_bethania", 34);
        lugares.put("gasolinera_gasoclub_santa_tecla", 36);
        lugares.put("uno_santa_tecla", 37);
        lugares.put("colegio_fatima", 38);
        
        /*Object[] elementos = {
            "hospital_climatosa",
            "liceo_jorge_adalberto_lagos",
            3,
            "centro_comercial_portal_plaza",
            5,
            39,
            7,
            1,
            "tessa",
            "policlinica_casa_de_la_salud",
            "policlinico_magisterial_de_santatecla",
            11,
            17,
            40,
            "escuela_de_comunicacion_monica_herrera",
            "escuela_santa_cecilia",
            "colegio_belen",
            "plaza_el_cafetalon",
            44,
            "academia_nacional_de_seguridad_publica",
            "alberto_masferrer_centro_escolar_catolico",
            "centro_escolar_marcelino_garcia_flamenco",
            "puma_energy",
            "hospital_nacional_san_rafael",
            "instituto_bethania",
            45,
            "gasolinera_gasoclub_santa_tecla",
            "uno_santa_tecla",
            "colegio_fatima"
        };*/

        // Imprimir el contenido del arreglo o el valor del HashMap
        for (Object elemento : rutaStrings) {
            if (elemento instanceof String) {
                Integer valor = lugares.get(elemento);
                if (valor != null) {
                    JButton boton = botonMap.get(valor);
                    if (boton != null) {
                        boton.setVisible(true);
                    }
                    System.out.println(valor);
                } else {
                    System.out.println(elemento);
                    JButton boton = botonMap.get((int) elemento);
                    if (boton != null) {
                        boton.setVisible(true);
                    }
                }
            } else {
                System.out.println(elemento);
                JButton boton = botonMap.get((int) elemento);
                if (boton != null) {
                    boton.setVisible(true);
                }
            }
        }
    }
    private void setButtonsInvisible() {
        JButton[] buttons = {
            Boton1, Boton2, Boton3, Boton4, Boton5, 
            Boton6, Boton7, Boton8, Boton9, Boton10, 
            Boton11, Boton12, Boton13, Boton14, Boton15, 
            Boton16, Boton17, Boton18, Boton19, Boton20, 
            Boton21, Boton22, Boton23, Boton24, Boton25, 
            Boton26, Boton27, Boton28, Boton29, Boton30, 
            Boton31, Boton32, Boton33, Boton34, Boton35, 
            Boton36, Boton37, Boton38, Boton39, Boton40, 
            Boton41, Boton42, Boton43, Boton44, Boton45, 
            Boton46
        };
        int counter = 1;
        botonMap = new HashMap<>();
        for(JButton button : buttons) {
            button.setVisible(false);
            botonMap.put(counter, button);
            counter++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Boton1;
    private JButton Boton10;
    private JButton Boton11;
    private JButton Boton12;
    private JButton Boton13;
    private JButton Boton14;
    private JButton Boton15;
    private JButton Boton16;
    private JButton Boton17;
    private JButton Boton18;
    private JButton Boton19;
    private JButton Boton2;
    private JButton Boton20;
    private JButton Boton21;
    private JButton Boton22;
    private JButton Boton23;
    private JButton Boton24;
    private JButton Boton25;
    private JButton Boton26;
    private JButton Boton27;
    private JButton Boton28;
    private JButton Boton29;
    private JButton Boton3;
    private JButton Boton30;
    private JButton Boton31;
    private JButton Boton32;
    private JButton Boton33;
    private JButton Boton34;
    private JButton Boton35;
    private JButton Boton36;
    private JButton Boton37;
    private JButton Boton38;
    private JButton Boton39;
    private JButton Boton4;
    private JButton Boton40;
    private JButton Boton41;
    private JButton Boton42;
    private JButton Boton43;
    private JButton Boton44;
    private JButton Boton45;
    private JButton Boton46;
    private JButton Boton5;
    private JButton Boton6;
    private JButton Boton7;
    private JButton Boton8;
    private JButton Boton9;
    private JButton jButton1;
    private JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
